### ISSUE TITLE
Patching/extending `lodash` causes problems in other libraries

### ISSUE THREAD

**Issue by fhemberger** [atomantic/hapi-and-healthy#20]
We were using hapi-and-healthy in one of our projects, when we noticed, that our kafka library wasn't working any longer. At first, I didn't ever think that this issue could be related to our healthcheck, but removing 'hapi-and-healthy' really was the one change that got our service working again.

I didn't get too much into details, but I think that extending/modifying `lodash`(e.g. with [`undermore`](https://github.com/atomantic/undermore)) might be the problem here, causing lodash's own `_.each` method to change their behavior.

Ref: https://github.com/oleksiyk/kafka/issues/121

**Comment by atomantic** [comment]
I removed undermore in favor of using native Buffer to string for the etag. I've revved this to 5.x.x as a major change because it breaks compatibility with node 0.x.x (not something I want to support anyway since those are dead versions of Node).

**Comment by fhemberger** [comment]
Great, thanks! Will give it a spin next week and see if it works out …
