### ISSUE TITLE
Tests are executed immediately but should they?

### ISSUE THREAD

**Issue by tiagoalves** [atomantic/hapi-and-healthy#27]
Hi,

I might be missing something but I believe that with the change to passing the custom health check tests as promises, the tests are executed immediately when the plugin is registered and they're never executed again.

Consider the included `demo.js` app changed with a `test.node` promise that always rejects.

```
const Hapi = require('hapi')
const pjson = require('./package.json')

const server = new Hapi.Server({
  port: 3192
})

server.register([{
  plugin: require('./index'),
  options: {
    env: process.env.APP_ENV || 'QA',
    name: pjson.name,
    test: {
      node: [
        new Promise((resolve, reject) => {
          console.log('Running test')
          reject(new Error('Oops'))
          // resolve('code checksum matches manifest')
        })
      ],
      features: [
        new Promise((resolve, reject) => {
          resolve('some feature or API endpoint passed tests')
        })
      ]
    },
    paths: ['v1', 'v2'],
    version: pjson.version
  }
}])
.then(() => server.start())
.then(() => console.log(`Server running at: ${server.info.uri} with ${pjson.version}`));
```

In this scenario, when the app starts, we immediately get the `"Running test"` output and an unhandled rejection `"Oops"`. And when we request the `/service-status` endpoint, we never see the `"Running test"` output again. The plugin is simply using the already stored test result.

My expected behaviour would be exactly the opposite (tests **only and always** run when requesting the `/service-status` endpoint).

Shouldn't the `test.node` and `test.features` arrays expect **functions** which return promises instead of the promises themselves?

Example:

```
    test: {
      node: [
        () => new Promise((resolve, reject) => {
          // do something
        }),
        () => new Promise((resolve, reject) => {
          // do something else
        })
      ]
      // ...
    }
```

The fix is simple but I'm hesitant to provide a PR because the change is not backwards-compatible. But that might not really matter since the plugin might not have ever worked correctly since the move to promises.

**Comment by atomantic** [comment]
Thanks for digging into this. I must have missed my first cup of coffee ;)

I was intending to break backward compatibility with the 6.x.x release (Major = backward breaking changes).

Bravo for catching that. 🎉
